# Generated by Django 5.0.14 on 2026-08-13 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0002_periodic_status_check'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lista de contatos',
                'verbose_name_plural': 'listas de contatos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_e164', models.CharField(db_index=True, max_length=20, verbose_name='número (E.164)')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='nome')),
                ('opt_out', models.BooleanField(default=False, verbose_name='optou por não receber')),
                ('ultimo_contato', models.DateTimeField(blank=True, null=True, verbose_name='último contato')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('listas', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contactlist')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ['-ultimo_contato', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('jid', models.CharField(db_index=True, max_length=100, verbose_name='JID')),
                ('membros_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de membros')),
                ('bot_e_admin', models.BooleanField(default=False, verbose_name='bot é admin')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='instances.instance')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jid_participante', models.CharField(blank=True, max_length=100, verbose_name='JID do participante')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='contacts.contact')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='contacts.group')),
            ],
            options={
                'verbose_name': 'membro do grupo',
                'verbose_name_plural': 'membros do grupo',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('cor', models.CharField(default='gray', max_length=20, verbose_name='cor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.tag')),
            ],
            options={
                'verbose_name': 'etiqueta do contato',
                'verbose_name_plural': 'etiquetas do contato',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='contacts', through='contacts.ContactTag', to='contacts.tag'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('instance', 'jid'), name='uniq_instance_jid'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'contact')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('owner', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='contacttag',
            unique_together={('contact', 'tag')},
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('owner', 'numero_e164'), name='uniq_owner_numero'),
        ),
    ]
