# Generated by Django 5.0.14 on 2026-08-13 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('instances', '0003_alter_instance_janela_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modo', models.CharField(choices=[('automatico', 'Automático (pré-disparo)'), ('manual', 'Manual')], max_length=20)),
                ('resultado', models.CharField(choices=[('sucesso', 'Removido com sucesso'), ('falha', 'Falha ao remover'), ('nao_era_admin', 'Bot já não era admin')], max_length=20)),
                ('detalhe', models.CharField(blank=True, max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_logs', to='contacts.group')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_logs', to='instances.instance')),
            ],
            options={
                'verbose_name': 'log de auto-demote',
                'verbose_name_plural': 'logs de auto-demote',
                'ordering': ['-created_at'],
            },
        ),
    ]
