# Generated by Django 5.0.14 on 2026-08-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0002_periodic_status_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.CharField(max_length=50, verbose_name='tipo do evento')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='id da mensagem (idempotência)')),
                ('payload', models.JSONField(verbose_name='payload bruto')),
                ('processado', models.BooleanField(default=False, verbose_name='processado')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='instances.instance')),
            ],
            options={
                'verbose_name': 'evento de webhook',
                'verbose_name_plural': 'eventos de webhook',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['instance', 'evento', 'processado'], name='webhooks_we_instanc_81b21f_idx')],
            },
        ),
    ]
