# Generated by Django 5.0.14 on 2026-08-13 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_adminactionlog'),
        ('instances', '0003_alter_instance_janela_fim_and_more'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('palavras_chave', models.CharField(max_length=255, verbose_name='palavras-chave (separadas por vírgula)')),
                ('modo', models.CharField(choices=[('ou', 'Qualquer palavra (OU)'), ('e', 'Todas as palavras (E)')], default='ou', max_length=10, verbose_name='modo')),
                ('etiqueta_nome', models.CharField(blank=True, max_length=50, verbose_name='nome da etiqueta a aplicar')),
                ('etapa_destino', models.CharField(blank=True, max_length=100, verbose_name='etapa destino (crm)')),
                ('prioridade', models.PositiveIntegerField(default=100, verbose_name='prioridade (menor = avaliado primeiro)')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('limite_repeticao_minutos', models.PositiveIntegerField(default=60, verbose_name='não repetir por (minutos)')),
                ('contato', models.ForeignKey(blank=True, help_text='Restringe o gatilho a este contato (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='contacts.contact')),
                ('grupo', models.ForeignKey(blank=True, help_text='Restringe o gatilho a este grupo (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggers', to='contacts.group')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='instances.instance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to=settings.AUTH_USER_MODEL)),
                ('resposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.message')),
            ],
            options={
                'verbose_name': 'gatilho',
                'verbose_name_plural': 'gatilhos',
                'ordering': ['prioridade', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mensagem_recebida', models.TextField(blank=True)),
                ('acoes_executadas', models.CharField(blank=True, max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_logs', to='contacts.contact')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='triggers.trigger')),
            ],
            options={
                'verbose_name': 'log de gatilho',
                'verbose_name_plural': 'logs de gatilho',
                'ordering': ['-created_at'],
            },
        ),
    ]
