# Generated by Django 5.0.14 on 2026-08-13 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_adminactionlog'),
        ('instances', '0003_alter_instance_janela_fim_and_more'),
        ('library', '0001_initial'),
        ('triggers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='followup_apos_horas',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='agendar follow-up após (horas)'),
        ),
        migrations.AddField(
            model_name='trigger',
            name='followup_mensagem',
            field=models.ForeignKey(blank=True, help_text='Se definida, agenda esta mensagem após o gatilho disparar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.message', verbose_name='mensagem de follow-up'),
        ),
        migrations.CreateModel(
            name='ScheduledMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_hora', models.DateTimeField(verbose_name='data e hora do envio')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('cancelada', 'Cancelada'), ('falha', 'Falha')], default='pendente', max_length=20)),
                ('origem', models.CharField(choices=[('manual', 'Agendado manualmente'), ('gatilho', 'Agendado por gatilho')], default='manual', max_length=20)),
                ('erro', models.CharField(blank=True, max_length=255)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='contacts.contact')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='instances.instance')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='library.message')),
            ],
            options={
                'verbose_name': 'mensagem agendada',
                'verbose_name_plural': 'mensagens agendadas',
                'ordering': ['data_hora'],
                'indexes': [models.Index(fields=['status', 'data_hora'], name='triggers_sc_status_95f694_idx')],
            },
        ),
    ]
