# Generated by Django 5.0.14 on 2026-08-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_alter_instance_janela_fim_and_more'),
        ('library', '0002_alter_message_folder'),
        ('triggers', '0003_periodic_scheduled_msgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmsg',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='instances.instance', verbose_name='instância'),
        ),
        migrations.AlterField(
            model_name='scheduledmsg',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='library.message', verbose_name='mensagem'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='instances.instance', verbose_name='instância'),
        ),
    ]
