# Generated by Django 5.0.14 on 2026-08-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instances', '0002_periodic_status_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(choices=[('rate_limit', 'Rate limit da Evolution'), ('falhas_consecutivas', 'Falhas consecutivas'), ('desconectado', 'Instância desconectada'), ('limite_diario', 'Limite diário atingido'), ('fora_janela', 'Fora da janela de operação')], max_length=30, verbose_name='motivo')),
                ('detalhe', models.CharField(blank=True, max_length=255, verbose_name='detalhe')),
                ('pausou_instancia', models.BooleanField(default=False, verbose_name='pausou a instância')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_events', to='instances.instance')),
            ],
            options={
                'verbose_name': 'evento de bloqueio',
                'verbose_name_plural': 'eventos de bloqueio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.DateField(verbose_name='data')),
                ('enviadas', models.PositiveIntegerField(default=0, verbose_name='enviadas')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_limits', to='instances.instance')),
            ],
            options={
                'verbose_name': 'limite diário',
                'verbose_name_plural': 'limites diários',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervalo_min_s', models.PositiveIntegerField(default=20, verbose_name='intervalo mínimo (s)')),
                ('intervalo_max_s', models.PositiveIntegerField(default=60, verbose_name='intervalo máximo (s)')),
                ('fator_escalonamento', models.FloatField(default=1.0, verbose_name='fator de escalonamento')),
                ('falhas_consecutivas', models.PositiveIntegerField(default=0, verbose_name='falhas consecutivas')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_settings', to='instances.instance')),
            ],
            options={
                'verbose_name': 'configuração de ritmo',
                'verbose_name_plural': 'configurações de ritmo',
            },
        ),
        migrations.AddConstraint(
            model_name='dailylimit',
            constraint=models.UniqueConstraint(fields=('instance', 'data'), name='uniq_instance_data'),
        ),
    ]
