# Generated by Django 5.0.14 on 2026-08-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiblock', '0001_initial'),
        ('instances', '0003_alter_instance_janela_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmupPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateField(verbose_name='início')),
                ('dias_total', models.PositiveIntegerField(default=14, verbose_name='duração (dias)')),
                ('dia_atual', models.PositiveIntegerField(default=1, verbose_name='dia atual')),
                ('limite_final', models.PositiveIntegerField(default=30, verbose_name='limite diário ao final (restaurado)')),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído')], default='em_andamento', max_length=20, verbose_name='status')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warmup_plans', to='instances.instance')),
            ],
            options={
                'verbose_name': 'plano de aquecimento',
                'verbose_name_plural': 'planos de aquecimento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarmupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia', models.PositiveIntegerField()),
                ('limite_do_dia', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='antiblock.warmupplan')),
            ],
            options={
                'verbose_name': 'atividade de aquecimento',
                'verbose_name_plural': 'atividades de aquecimento',
                'ordering': ['-created_at'],
            },
        ),
    ]
