# Generated by Django 5.0.14 on 2026-08-13 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('instances', '0002_periodic_status_check'),
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'script',
                'verbose_name_plural': 'scripts',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ScriptStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordem', models.PositiveIntegerField(verbose_name='ordem')),
                ('tipo', models.CharField(choices=[('mensagem', 'Enviar mensagem'), ('delay', 'Aguardar (delay fixo)'), ('aguardar_resposta', 'Aguardar resposta'), ('condicao', 'Condição (se a resposta contiver X)'), ('mudar_etapa', 'Mudar etapa do lead')], max_length=20, verbose_name='tipo')),
                ('delay_s', models.PositiveIntegerField(blank=True, null=True, verbose_name='delay (segundos)')),
                ('timeout_h', models.PositiveIntegerField(blank=True, default=48, null=True, verbose_name='timeout (horas)')),
                ('condicao_contem', models.CharField(blank=True, max_length=100, verbose_name='resposta contém')),
                ('etapa_destino', models.CharField(blank=True, max_length=100, verbose_name='etapa destino (crm)')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.message')),
                ('proximo_passo', models.ForeignKey(blank=True, help_text='Passo para onde ir se a condição casar (tipo = condição).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alvo_de', to='scripts.scriptstep')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scripts.script')),
            ],
            options={
                'verbose_name': 'passo do script',
                'verbose_name_plural': 'passos do script',
                'ordering': ['script', 'ordem'],
                'unique_together': {('script', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='ScriptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('em_andamento', 'Em andamento'), ('aguardando_resposta', 'Aguardando resposta'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('erro', 'Erro')], default='em_andamento', max_length=20, verbose_name='status')),
                ('origem', models.CharField(choices=[('teste', 'Teste manual'), ('campanha', 'Campanha')], default='teste', max_length=20, verbose_name='origem')),
                ('aguardando_desde', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_runs', to='contacts.contact')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_runs', to='instances.instance')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scripts.script')),
                ('passo_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scripts.scriptstep')),
            ],
            options={
                'verbose_name': 'execução de script',
                'verbose_name_plural': 'execuções de script',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contact', 'status'], name='scripts_scr_contact_8fd42f_idx')],
            },
        ),
    ]
