# Generated by Django 5.0.14 on 2026-08-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrun',
            name='ultimo_message_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
