# Generated by Django 5.0.14 on 2026-08-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0002_scriptrun_ultimo_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptrun',
            name='contexto_extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
