# Generated by Django 5.0.14 on 2026-08-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_alter_message_folder'),
        ('scripts', '0003_scriptrun_contexto_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptstep',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.message', verbose_name='mensagem'),
        ),
    ]
