# Generated by Django 5.0.14 on 2026-08-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_alter_scriptstep_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptstep',
            name='condicao_contem',
            field=models.CharField(blank=True, help_text='Casa se QUALQUER um dos termos aparecer na resposta. Maiúsculas e acentos são ignorados — "nao" encontra "Não". Ex.: pode, quero, sim, manda, bora', max_length=255, verbose_name='resposta contém (separe por vírgula)'),
        ),
    ]
