# Generated by Django 5.0.14 on 2026-08-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_alter_scriptstep_condicao_contem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptstep',
            name='condicao_contem',
            field=models.CharField(blank=True, help_text='Casa se QUALQUER um dos termos aparecer na resposta. Maiúsculas e acentos são ignorados — "nao" encontra "Não". Ex.: nao, nao quero, sem interesse. Evite termos de 1 ou 2 letras: a busca é por trecho, então "n" casaria com "mandar".', max_length=255, verbose_name='resposta contém (separe por vírgula)'),
        ),
    ]
