# Generated by Django 5.0.14 on 2026-08-14 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_alter_scriptstep_condicao_contem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptstep',
            name='proximo_passo',
            field=models.ForeignKey(blank=True, help_text='Para onde PULAR se a condição casar (tipo = condição). Quem não casar segue na ordem normal — por isso condicione nos termos negativos e pule a mensagem que não deve ser enviada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alvo_de', to='scripts.scriptstep', verbose_name='próximo passo'),
        ),
    ]
