# Generated by Django 5.0.14 on 2026-08-14 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('scripts', '0007_alter_scriptstep_proximo_passo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptstep',
            name='condicao_ia_descricao',
            field=models.TextField(blank=True, help_text='O que conta como positivo — ex.: "o contato demonstrou interesse em receber o link do grupo".', verbose_name='descrição para a IA'),
        ),
        migrations.AddField(
            model_name='scriptstep',
            name='ia_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.aiconfig', verbose_name='configuração de IA'),
        ),
        migrations.AddField(
            model_name='scriptstep',
            name='usar_ia',
            field=models.BooleanField(default=False, help_text='Só vale para o tipo "condição". Se a IA falhar, cai no matching por palavra-chave abaixo.', verbose_name='usar IA para avaliar a condição'),
        ),
    ]
