# Generated by Django 5.0.14 on 2026-08-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_scriptstep_condicao_ia_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='usar_ia',
            field=models.BooleanField(default=True, help_text='Interruptor geral: desligado, nenhum passo deste script consulta IA, mesmo configurada.', verbose_name='usar IA nos passos de condição'),
        ),
    ]
