# Generated by Django 5.0.14 on 2026-08-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_script_usar_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptstep',
            name='condicao_ia_descricao',
            field=models.TextField(blank=True, help_text='Descreva a MESMA condição do campo "resposta contém", em português: a IA decide se a resposta se encaixa nela, e quem se encaixa PULA para o próximo passo. Como o pulo leva à mensagem que não deve ser enviada, descreva a recusa — ex.: "o contato recusou o convite ou pediu para parar de receber mensagens".', verbose_name='descrição para a IA'),
        ),
    ]
