# Generated by Django 5.0.14 on 2026-08-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0010_alter_scriptstep_condicao_ia_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptstep',
            name='tipo',
            field=models.CharField(choices=[('mensagem', 'Enviar mensagem'), ('delay', 'Aguardar (delay fixo)'), ('aguardar_resposta', 'Aguardar resposta'), ('condicao', 'Condição (se a resposta contiver X)'), ('mudar_etapa', 'Mudar etapa do lead'), ('encerrar', 'Encerrar (fim deste ramo)')], max_length=20, verbose_name='tipo'),
        ),
    ]
