# Generated by Django 5.0.14 on 2026-08-13 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('evolution_instance_name', models.SlugField(max_length=100, unique=True, verbose_name='nome na Evolution')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('status', models.CharField(choices=[('desconectado', 'Desconectado'), ('aguardando_qr', 'Aguardando QR'), ('conectado', 'Conectado'), ('banido', 'Banido')], default='desconectado', max_length=20, verbose_name='status')),
                ('limite_diario', models.PositiveIntegerField(default=30, verbose_name='limite diário de envios')),
                ('janela_inicio', models.TimeField(default='08:00', verbose_name='início da janela de envio')),
                ('janela_fim', models.TimeField(default='21:00', verbose_name='fim da janela de envio')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('ultimo_status_em', models.DateTimeField(blank=True, null=True, verbose_name='último status em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'instância',
                'verbose_name_plural': 'instâncias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(max_length=20)),
                ('detalhe', models.CharField(blank=True, max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='instances.instance')),
            ],
            options={
                'verbose_name': 'evento de instância',
                'verbose_name_plural': 'eventos de instância',
                'ordering': ['-created_at'],
            },
        ),
    ]
