# Generated by Django 5.0.14 on 2026-08-13 20:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_periodic_status_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='janela_fim',
            field=models.TimeField(default=datetime.time(21, 0), verbose_name='fim da janela de envio'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='janela_inicio',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='início da janela de envio'),
        ),
    ]
