# Generated by Django 5.0.14 on 2026-08-13 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('instances', '0003_alter_instance_janela_fim_and_more'),
        ('scripts', '0002_scriptrun_ultimo_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendada', 'Agendada'), ('em_andamento', 'Em andamento'), ('pausada', 'Pausada'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20, verbose_name='status')),
                ('agendado_para', models.DateTimeField(blank=True, null=True, verbose_name='agendado para')),
                ('antiduplicacao_dias', models.PositiveIntegerField(default=30, verbose_name='anti-duplicação (dias)')),
                ('filtro_publico', models.CharField(choices=[('todos', 'Todos os contatos do público'), ('nao_respondeu', 'Somente quem ainda não respondeu')], default='todos', max_length=20, verbose_name='filtro de público')),
                ('remover_admin_antes', models.BooleanField(default=False, verbose_name='remover admin do bot antes de disparar')),
                ('contatos_avulsos', models.ManyToManyField(blank=True, related_name='campanhas_avulsas', to='contacts.contact')),
                ('grupos', models.ManyToManyField(blank=True, related_name='campanhas', to='contacts.group')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='instances.instance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='scripts.script')),
            ],
            options={
                'verbose_name': 'campanha',
                'verbose_name_plural': 'campanhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviada', 'Enviada'), ('respondida', 'Respondida'), ('falha', 'Falha'), ('pulada', 'Pulada (anti-duplicação/opt-out)')], default='pendente', max_length=20, verbose_name='status')),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.CharField(blank=True, max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='campaigns.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='contacts.contact')),
                ('origem_grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contacts.group')),
                ('script_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_contact', to='scripts.scriptrun')),
            ],
            options={
                'verbose_name': 'contato da campanha',
                'verbose_name_plural': 'contatos da campanha',
            },
        ),
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('falha', 'Falha')], max_length=20, verbose_name='status')),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='id da mensagem (Evolution)')),
                ('erro', models.TextField(blank=True)),
                ('campaign_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='campaigns.campaigncontact')),
            ],
            options={
                'verbose_name': 'log de entrega',
                'verbose_name_plural': 'logs de entrega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaigncontact',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_77ea88_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigncontact',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='uniq_campaign_contact'),
        ),
    ]
