# Generated by Django 5.0.14 on 2026-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_periodic_failure_rate_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='remover_admin_antes',
            field=models.BooleanField(default=False, help_text='Reconsulta os grupos no WhatsApp antes do envio para garantir que nenhum administrador receba a mensagem, e remove o próprio bot da administração dos grupos onde ele for admin.', verbose_name='revalidar administradores dos grupos antes de disparar'),
        ),
    ]
