# Generated by Django 5.0.14 on 2026-08-14 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_remover_admin_antes'),
        ('instances', '0003_alter_instance_janela_fim_and_more'),
        ('scripts', '0004_alter_scriptstep_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='instances.instance', verbose_name='instância'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='scripts.script', verbose_name='script'),
        ),
    ]
