# Generated by Django 5.0.14 on 2026-08-14 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('provider', models.CharField(choices=[('anthropic', 'Claude (Anthropic)'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('openai_compativel', 'Compatível com OpenAI (URL própria)')], max_length=20, verbose_name='provedor')),
                ('modelo', models.CharField(help_text='Ex.: claude-opus-5, gpt-5, gemini-2.5-flash.', max_length=100, verbose_name='modelo')),
                ('api_key_cifrada', models.TextField(verbose_name='api key (cifrada)')),
                ('base_url', models.CharField(blank=True, help_text='Obrigatório só para "Compatível com OpenAI" (ex.: OpenCode Zen, OpenRouter).', max_length=255, verbose_name='URL base')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configuração de IA',
                'verbose_name_plural': 'configurações de IA',
                'ordering': ['nome'],
            },
        ),
    ]
